build.zig
build.zig.zon

With these changes, it is possible to use the built in zig package manager to make a zig program based on zap.
For an example project, see https://github.com/qbradley/kahawatamu, which currently is just the zap hello world but in its own repository.  Clone it and run the following commands will automatically pull down and build zap and facil.io as part of creating the exe:
```
git clone https://github.com/qbradley/kahawatamu
cd kahawatamu
zig build run
```
In kahawatamu I had to add both zap and facil.io as dependencies, as I found a way to reference a C project as a static library and a zig projects as a module, but I did not find a way in the current zig code for a package exporting a module to automatically include a static library when referenced.
Maybe it is too soon for these …

Configure zap and facil.io as zig packages

---

src/zap.zig

I found these as I was unable to call zap.SimpleRequest.setContentType.

Make ContentType, HttpParam, and ListenError public

---

examples/endpoint/endpoint.zig

zig 0.11.0-dev.3203+7cf2cbb33 has updated the json api. I've updated to use the new parseFromSlice call which basically does the init and deinit of the json.Scanner so we don't have to do it as we had to for json.TokenStream.

update endpoint example to the new json api

---

src/http_auth.zig

Browser will delete the cookie automatically when the max-age is set to -1.

cookie Max-Age should be set to -1 when invalidating the cookie

---

.gitignore
wrk/csharp/Program.cs
wrk/csharp/Properties/launchSettings.json
wrk/csharp/csharp.csproj
wrk/measure.sh

I was curious about C# AOT using [dotnet 8 preview](https://dotnet.microsoft.com/en-us/download/dotnet/8.0).  The numbers are about the same for `C#` `Go` `Rust (Axum)`. I'm wondering if there is something stopping wrk from performing more requests. I'm using a M1 Pro mac. 
I couldn't build `Zig` from HEAD 😢

Add C# AOT version for comparison

---

examples/hello_json/hello_json.zig
src/deps/cimport.zig
src/fio.zig
src/util.zig
src/websockets.zig
src/zap.zig
tools/Manifest.zig

Once again, for readability's sake, the Zig api changed again:
Basically, `@as(A, @ptrCast(@alignCast(@alignOf(A), B))))` is changed to
`@as(A, @ptrCast(@alignCast(B)))`.
And some other changes to @intCast, @bitCast, @truncate
such as the following:
old
```zig
return ((((__bsx & @as(c_uint, 4278190080)) >> @intCast(@import("std").math.Log2Int(c_uint), 24)) | ((__bsx & @as(c_uint, 16711680)) >> @intCast(@import("std").math.Log2Int(c_uint), 8))) | ((__bsx & @as(c_uint, 65280)) << @intCast(@import("std").math.Log2Int(c_uint), 8))) | ((__bsx & @as(c_uint, 255)) << @intCast(@import("std").math.Log2Int(c_uint), 24));
```
new
```zig
return ((((__bsx & @as(c_uint, 4278190080)) >> @as(@import("std").math.Log2Int(c_uint), @intCast(24))) | ((__bsx & @as(c_uint, 16711680)) >> …
```

Update to use the new alignCast where the alignOf is not needed anymore

---

examples/mustache/mustache.zig
src/mustache.zig
src/tests/test_mustache.zig

- `mustache.zig` now returns a `Mustache` struct. This allows functions to be called on the mustache instance, e.g. `zap.mustacheFree(mustache)` -> `mustache.free()`.
- Updated mustache example.
- Added doc strings to majority of mustache functions.
- Updated mustache tests.

Updated `mustache.zig` to be more Zig like

---

src/mustache.zig

- Updated `Mustache.fiobjectify` to be private
- Updated docstrings on `Mustache.build`
- Renamed `Mustache.handler` -> `Mustache.handle`
- Added docstrings for `Mustache.fiobjectify` and `Mustache.handle`
- Removed `Mustache.status`

Mustache doc comments

---

README.md
build.zig

Also includes a small modification to the readme for instructions how to pass it through from any project that depends on zap.
Would resolve #62 if accepted.
Lemme know what ya think.

Re-add -Dopenssl to zap build

---

examples/hello2/hello2.zig
examples/hello_json/hello_json.zig
src/endpoint.zig
src/http.zig
src/request.zig
src/zap.zig

This PR does the following:
- `Request.method` becomes an `std.http.Method enum` so developers can use switch statements and other better syntax on it
- `Request.method_str` is the original string representation of the http method
Why both? 
Quality of life. Since there is no easy and concise way of printing Enum in Zig, one will make request easier to compare and the other will be easier to print. Examples also have been updated accordingly. This decision was made based on my personal need without approval of anyone, so please do feel free to reject this PR, request changes, or make criticisms if this change doesn't feel fit for the project.
What happens if the HTTP method is none of the one listed? 
Well, it shouldn't happen, because I did see a part of Zap's (or facil's I can't …

Use std.http.Method for Request.method

---

build.zig

Yes, it is already in README. I just thought it would be nice if the build system explicitly fails Windows builds.
Test package available [[here](https://github.com/Chiissu/zap/releases/tag/v0.6.0-alpha3)].
Just 2 LOC, thanks to Zig's beautiful build system.
Just wanna mention #74

Provide Windows error message

---

examples/hello_json/hello_json.zig

hello_json example failed to compile because of optional unwrap. Fixed by removing the ".?"

fixed unneeded optional unwrap in hello_json

---

src/request.zig

Adds a function to get one of the common headers that facil.io pre-allocates space for. For context, I was trying to get the "Accept" field and `request.getHeader("Accept")` didn't work. It's easy enough to work around, but I think having `getHeaderCommon` would be a slightly nicer interface.

feat: add getHeaderCommon

---

examples/senderror/senderror.zig
src/request.zig

This should produce more usable error messages. The error messages before this were pointing at zap runtime functions, instead of at the code that produced the error.
Note that this is a breaking change, as I modified the `sendError` to take StackTrace argument. This is in part because I am unsure if `@errorReturnTrace` will be overwritten by the other function calls that can return an error, so I take the StackTrace by value.
Before, the stack traces looked like this:
```
ERROR: error.NoSeries
/home/geemili/.cache/zig/p/1220a5a1e6b18fa384d8a98e5d5a25720ddadbcfed01da2e4ca55c7cfb3dc1caa62a/src/request.zig:344:41: 0x2f6217 in _internal_sendError (raptor)
try std.debug.writeCurrentStackTrace(writer, debugInfo, ttyConfig, null);
^
/home/geemili/.cache/zig/p/1220a5a1e6b18fa384d8a98e5d5a25720dda …
```

fix: use error return trace in senderror

---

build.zig
src/http.zig
src/request.zig
tools/docserver.zig

Makes `run-docserver` use the generated files as the docs root automatically. Adds 2 new functions, `zap.mimetypeRegister` and `zap.mimetypeClear`. This was needed to serve the webassembly modules from the docs in a way browsers will accept.

Fix docserver, Wrap http_mimetype_register and http_mimetype_clear

---

README.md
build.zig

This means that all downstream users can simply put:
```zig
exe.root_module.addImport("zap", zap.module("zap"))`
```
in their `build.zig` instead of
```zig
exe.root_module.addImport("zap", zap.module("zap"));
exe.linkLibrary(zap.artifact("facil.io"));
```
This change should be backwards compatible. I updated some local code to use this change, and it didn't require any modifications to that `build.zig`. That means the old method will still work, but users will no longer have to manually link `facil.io`.

feat: streamline depending on zap by linking facil.io to module

---

src/http.zig

using MDN as a reference.
I added new status codes as described by [rfc9110][1] and [MDN][2]. Some were renamed since rfc7231, so I renamed them. It feels like good practice to keep up with spec, huh?
[1]: https://datatracker.ietf.org/doc/html/rfc9110#name-status-codes
[2]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

update http.zig to rfc9110

---

wrk/measure.sh
wrk/zighttpz/build.zig
wrk/zighttpz/build.zig.zon
wrk/zighttpz/main.zig

Hello,
This adds http.zig to the benchmarks. The library has undergone a number of changes and, in my measurements, comes very close to Zap. I think this is worth highlighting as most pure Zig implementations are very slow.
(I see that there's already an http.zig branch, but it's quite old and can be deleted)

add http.zig to benchmarks

---

build.zig
build.zig.zon
examples/accept/accept.zig
src/http.zig
src/request.zig
src/zap.zig

Parses the Accept field from the header to return the ranked list of content types the client expects. I'd like feedback on the API - it doesn't seem quite right to me yet.

Parse Accept

---

build.zig

By replacing the linux only `std.posix.getenv` with the cross platform `std.process.getEnvVarOwned` in `build.zig` it is now possible to cross compile zap on a windows host.

Fix build.zig to allow cross compilation on windows

---

build.zig
facil.io/build.zig

LazyPath has been deprecated in Zig 0.12 and in
the Zig master this breaks zig build.

Remove deprecated path

---

src/mustache.zig

This small PR includes the Mustache build results in the public API to allow developers to better annotate types and pass the build result around if needed.
The discussion for this originated on Discord, so I'll include the important bits below for future readers:
> **me:** Is there a design decision behind why the `MustacheBuildResult` type isn't marked public?
> **renerocksai:** At the time, I probably thought it wouldn't be necessary to make it public, as it is returned by a pub fn anyway, which makes it kind-of-public. This choice makes it impossible (I think) to declare variables of this type in user code and encourages just assigning the result of the build function. 
>
> Do you have a need for `var x : zap.Mustache.MustacheBuildResult = .{}`  and assigning later or similar? Ah, …

include BuildResult in public Mustache API

---

examples/middleware_with_endpoint/middleware_with_endpoint.zig
src/middleware.zig

This adds options to the `EndpointHandler` type to optionally use endpoint routing logic.
This fixes #119.
@renerocksai if this approach is reasonable, I'll work on updating the any documentation or examples that reference the code before marking this PR complete.

Create options for EndpointHandler

---

README.md

Deduplicate references to building with master, and remove outdated reference to future release of 0.13. I thought the `A: `s looked unnecessary as well.

Cleanup FAQ of README.md

---

.gitignore
facil.io/lib/facil/http/websockets.c

This PR fixes a compiler warning in the `websockets.c` file regarding a _deprecated non-prototype function declaration_. The warning occurs because the `new_websocket` function is initially declared without a prototype but is later defined with a parameter.
The warning looks like this:
```logs
facil.io/lib/facil/http/websockets.c:99:14: warning: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a subsequent definition [-Wdeprecated-non-prototype]
99 | static ws_s *new_websocket();
|              ^
facil.io/lib/facil/http/websockets.c:305:14: note: conflicting prototype is here
305 | static ws_s *new_websocket(intptr_t uuid) {
|              ^
```
I encountered this issue while integrating Zap …

Fix deprecated warning in facil.io

---

src/router.zig

I took a quick stab at trying to fix #121. 
This is the first time I've played with type introspection in Zig, so please let me know if there's a better way to do this.

Add type checking to `simple_router`'s `handle_func`

---

examples/app/auth.zig
examples/app/basic.zig
examples/app/errors.zig
examples/endpoint/error.zig
examples/endpoint/stopendpoint.zig
examples/endpoint/userweb.zig
examples/endpoint_auth/endpoint_auth.zig
examples/middleware_with_endpoint/middleware_with_endpoint.zig
src/App.zig
src/endpoint.zig
src/middleware.zig
src/tests/test_auth.zig

This pull request introduces support for the HTTP `HEAD` method across various endpoints and structures in the codebase. It ensures that `HEAD` requests are properly handled in both core functionality and examples, while also updating related authentication and middleware logic.
* Added `head` method to multiple endpoint structs, including `MyEndpoint`, `SimpleEndpoint`, `ErrorEndpoint`, `StopEndpoint`, `HtmlEndpoint`, and `UserWeb`, enabling them to handle `HEAD` requests. (`[[1]](diffhunk://#diff-146a459eb4ae8d10d2699ccb000c4f6a750d9a8bd4c25290d0b212db3f74dec3R68)`, `[[2]](diffhunk://#diff-3bdafe3135ec8926afcba258bffc5ebacb513f1a41b508e91f6bbaf0b40aad10R69)`, `[[3]](diffhunk://#diff-76e6ff01f25c8c789cc21480ddc2b2e0418780e50a9ae5f14041199c079c7faeR56)`, …

fix: add missing head handler for EndpointType

---

examples/bindataformpost/bindataformpost.zig
examples/cookies/cookies.zig
examples/endpoint/main.zig
examples/http_params/http_params.zig
src/http_auth.zig
src/request.zig

From this example:
```
debug(request): /notavideofile
error(process): /home/joey/MultiMedia/notavideofile: error.FFmpegFailure (after 47.208ms)
debug(zap): setting content-type to application/json
debug(request): /video.mp4
```
Zap was adding an additional newline to the log lines now that Zig's standard logging facilities are used. It was quite inconsistent, too.

Log: remove additional newlines due to Zig's default log fn

---

examples/app/auth.zig
examples/app/basic.zig
examples/app/errors.zig
src/App.zig

Make `get`, `post`, ... methods optional in endpoint. Check whether these method exist at comptime. When no corresponding method is provided, the handler simply return immediately.
Since it uses comptime, hopefully it should not add any checks at runtime.
Also since App shares a global state (`_static`), I think it makes more sense NOT accept an `app` instance in the apis. So:
old:
```zig
var app = App.init(...);
try app.register(...);
```
proposal:
```
App.init(...);
App.register(...);
```
See `examples/app/`.

Provide defaults to unimplemented methods in endpoints for App style api.
